#!/bin/bash
echo "🔒 ATP SECURITY DEPLOYMENT - REFRESHED COMMAND"
echo "=============================================="
echo ""
echo "COPY AND RUN THIS EXACT COMMAND IN YOUR TERMINAL:"
echo ""
echo "───────────────────────────────────────────────"
echo 'ssh root@165.227.13.206 "cd /opt/atp && git fetch origin && git reset --hard origin/main && npm install && npm run build && pm2 restart atp-website && pm2 list && echo TESTING... && sleep 2 && curl -I https://agenttrustprotocol.com/policies | head -1"'
echo "───────────────────────────────────────────────"
echo ""
echo "Expected result after running:"
echo "  • PM2 should show atp-website as 'online'"
echo "  • Test should return: HTTP/1.1 403 Forbidden"
echo ""
echo "If it still returns 200 OK, the deployment path may be different."
